### PR TITLE
ncm-ceph: fix user for known_hosts and fix output for destroy and restart

### LINKED ISSUE #585: ncm-ceph: manual commands for removing monitors
When removing a monitor from my cluster, the component told me this:
```
[INFO] Commands to be run manually:
[INFO] su - ceph -c /usr/bin/ceph-deploy --cluster ceph fqdn destroy mon2
[INFO] su - ceph -c /usr/bin/ceph-deploy --cluster ceph mon destroy mon2
[INFO] su - ceph -c /usr/bin/ceph-deploy --cluster ceph config destroy mon2
```
What I actually needed to run was
```bash
su - ceph -c "/usr/bin/ceph-deploy --cluster ceph mon destroy mon2.example.org"
```

### PR DESCRIPTION
**Pull request by kwaegema**
fixes #585 and #586

### CODE REVIEW

File: ncm-ceph/src/main/perl/Ceph/commands.pm [hunk 1]
```diff
@@ -161,8 +161,8 @@ sub ssh_known_keys {
         if (!$lines) {
```
Comment (piojo) [inline ncm-ceph/src/main/perl/Ceph/commands.pm]: Sorry for looking at something that is not in the diff, but whaty's the purpose of this?  It looks like you only care on whether the output is empty?

Comment (kwaegema) [inline ncm-ceph/src/main/perl/Ceph/commands.pm]: ($key_accept eq 'first') means: only add the ssh key blindy if it is not already there. If it is there, it will not replace it, it only does that when key_accept is 'always'

Comment (piojo) [inline ncm-ceph/src/main/perl/Ceph/commands.pm]: Sorry, github isn't showing you what I meant.  I meant this chunk (expand the context):

```perl  
my $cmd = ['/usr/bin/ssh-keygen', '-F', $host];
my $output = $self->run_command_as_ceph($cmd);
# Count the lines of the output
my $lines = $output =~ tr/\n//;
if (!$lines) {
```

Why do you need to count lines at all?  It looks to me like you're doing something if there is output and something if there isn't.

Comment (kwaegema) [inline ncm-ceph/src/main/perl/Ceph/commands.pm]: It needs to trim the newlines, because of the behaviour of ssh-keygen:

[kwaegema@daenerys ~]$ bla=`` `ssh-keygen -F gastlyf.ugent.be` ``
[kwaegema@daenerys ~]$ echo $bla

[kwaegema@daenerys ~]$

File: ncm-ceph/src/main/perl/Ceph/commands.pm [hunk 2]
```diff
@@ -161,8 +161,8 @@ sub ssh_known_keys {
...
             $cmd = ['/usr/bin/ssh-keyscan', $host];
             my $key = $self->run_command_as_ceph($cmd);
-            my $fh = CAF::FileEditor->open("$homedir/.ssh/known_hosts",
-                                           log => $self);
+            my $fh = CAF::FileEditor->open("$cephusr->{homeDir}/.ssh/known_hosts",
+                                           log => $self, owner => $cephusr->{uid}, group => $cephusr->{gid} );
```
Comment (stdweird) [inline ncm-ceph/src/main/perl/Ceph/commands.pm]: one attribute per line, end with `,`

**Comment by stdweird** [comment]
@kwaegema minor remark and update branch

**Comment by stdweird** [comment]
rebase instead of update branch

**Comment by kwaegema** [comment]
done

**Comment by kwaegema** [comment]
@stdweird rebased again

**Comment by jrha** [comment]
@gvasilak can you have a look over this?

**Comment by jrha** [comment]
Also @GRyall...
