### PR TITLE
ncm-afsclt: fix handling of size AUTOMATIC

### LINKED ISSUE #815: ncm-afsclt fails if cache size is set to AUTOMATIC
`nfs-afsclt`, since changes introduced in Dec. 2015 (ca8692b8c787da2dd80d21f1e174011c7831a13b), fails if the cache size is set to AUTOMATIC when parsing the existing `cacheinfo` file and when doing some sanity checks on the size.

Should be considered as a showstopper for [16.6.0-rc4](https://github.com/quattor/release/issues/253) (missed at LAL in 16.2 in fact as we didn't deploy 16.2).

### PR DESCRIPTION
**Pull request by jouvin**
Fixes #815.

### CODE REVIEW

**Comment by jrha** [comment]
That and many sites have stopped using AFS.

**Comment by jouvin** [comment]
Unit tests added for test configurations. Uncovered a few potential issues, in particular if the initial `cacheinfo` file was empty.

File: ncm-afsclt/src/main/perl/afsclt.pm [hunk 1]
```diff
@@ -106,34 +111,36 @@ sub Configure_Cache {
         $self->warn("Cannot determine current AFS cache size, changing only config file");
     }
 
-    my $afs_cacheinfo_fh = CAF::FileEditor->new( $AFS_CACHEINFO, log => $self ); # TODO use FileReader
-    $afs_cacheinfo_fh->cancel();
-    if ( "$afs_cacheinfo_fh" =~ m;^([^:]+):([^:]+):(\d+)$; ) {
+    my $afs_cacheinfo_fh = CAF::FileReader->new( $AFS_CACHEINFO, log => $self );
+    $self->debug(2, "$AFS_CACHEINFO current contents: >>>$afs_cacheinfo_fh<<<");
```
Comment (stdweird) [inline ncm-afsclt/src/main/perl/afsclt.pm]: only in else block? (and in that case, maybe in the error message)

File: ncm-afsclt/src/main/perl/afsclt.pm [hunk 2]
```diff
@@ -106,34 +111,36 @@ sub Configure_Cache {
...
-    # sanity check - don't allow cachesize bigger than 95% of a partition size
-    $proc = CAF::Process->new( [ "df", "-k", $file_cachemount ], log => $self, keeps_state => 1 );
-    foreach my $line ( split ( "\n", $proc->output() ) ) {
-        if ($line =~ m{^.*?\s+(\d+)\s+\d+\s+\d+\s+\d+%\s+(.*)}) {
-            my $disk_cachesize = $1;
-            my $mount          = $2;
-            if ( $mount eq $file_cachemount && $new_cache > 0.95 * $disk_cachesize ) {
-                $self->error("Cache size ($disk_cachesize) on $mount cannot exceed 95% of its partition size. Not changing.");
-                return 1;
+    unless ( $new_cache eq "AUTOMATIC" ) {
```
Comment (stdweird) [inline ncm-afsclt/src/main/perl/afsclt.pm]: use `if ($new_cache ne "AUTOMATIC") {` ?

File: ncm-afsclt/src/main/perl/afsclt.pm [hunk 3]
```diff
@@ -83,16 +83,21 @@ sub Configure_Cache {
     my $file_cache      = 0;     # how much cache is actually configured now in the config file
     my $file_cachemount = '';    # where should the cache be mounted per config file
     my $new_cache       = 0;     # in 1k blocks.
-    my $file_afsmount   = '';
+    my $file_afsmount   = '/afs';
```
Comment (stdweird) [inline ncm-afsclt/src/main/perl/afsclt.pm]: why is this needed?

File: ncm-afsclt/src/test/resources/automatic.pan [hunk 4]
```diff
@@ -0,0 +1,9 @@
+object template automatic;
+
```
Comment (stdweird) [inline ncm-afsclt/src/test/resources/automatic.pan]: it would also be nice to do some schema tests, something similar like https://github.com/quattor/configuration-modules-core/blob/master/ncm-autofs/src/test/resources/maps.pan#L6 (with the lines above an below).
you will also have to replace https://github.com/quattor/configuration-modules-core/blob/master/ncm-afsclt/src/main/pan/components/afsclt/schema.pan#L8 with https://github.com/quattor/configuration-modules-core/blob/master/ncm-autofs/src/main/pan/components/autofs/schema.pan#L7

File: ncm-afsclt/src/main/perl/afsclt.pm (hunk 3 above)
Comment (stdweird) [inline ncm-afsclt/src/main/perl/afsclt.pm]: ok, i sort of understand, this is for the empty file case.
better to use add the default values as readonly on top the module, and do
```perl
use Readonly;
Readonly my $DEFAULT_AFSMOUNT => '/afs';

...
my $file_afsmount   = $DEFAULT_AFSMOUNT;
```

and probably similar for file_cachemount and new_cache.

```

**Comment by stdweird** [comment]
some minor remarks, LGTM otherwise

**Comment by jouvin** [comment]
@stdweird thanks as usual for the remarks. I'll address them tomorrow. Most of them in fact apply to the original code and its last modification in december. I tried to address an urgent problem but didn't attempt to fix all the possible ones. I'll also try to improve a little bit the unit tests.

File: ncm-afsclt/src/main/perl/afsclt.pm (hunk 1 above)
Comment (jouvin) [inline ncm-afsclt/src/main/perl/afsclt.pm]: In fact, I realized that my mod was wrong because if was no longer possible to override value in `cacheinfo` by the Quattor configuration. `cacheinfo` should only be used as default values. fixed.

File: ncm-afsclt/src/main/perl/afsclt.pm (hunk 3 above)
Comment (jouvin) [inline ncm-afsclt/src/main/perl/afsclt.pm]: Done.

**Comment by jouvin** [comment]
Should be ok now. Remarks addresssed. Unit tests improved. `cacheinfo` values used only as default values.

File: ncm-afsclt/src/test/resources/automatic.pan (hunk 4 above)
Comment (jouvin) [inline ncm-afsclt/src/test/resources/automatic.pan]: Done

**Comment by jouvin** [comment]
@ajf8 you may want to have a look and to check that this doesn't break anything for you, compared to the last modifications you committed in December 2015.

File: ncm-afsclt/src/main/pan/components/afsclt/schema.pan [hunk 5]
```diff
@@ -5,21 +5,20 @@
...
-   				 # "Shall AFS client be active ?"
-   "afsd_args"  ? string{} # /etc/afsd.args values for rc.afs
+   "thiscell"   : string         # AFS home cell
+   "thesecells" ? string[]       # Cell list to authenticate to
+   "settime"    ? boolean        # Shall AFS client sync sys time?
+   "cellservdb" ? string         # Where Master CellServDB can be found
+   "afs_mount"  ? string         # AFS mount point (e.g. /afs)
+   "cachemount" ? string         # AFS cache location (/usr/vice/etc/cache)
+   "cachesize"  ? string         # AFS cache size in kB
+   "enabled"    : string with match (SELF, 'yes|no') # Shall AFS client be active ?
```
Comment (stdweird) [inline ncm-afsclt/src/main/pan/components/afsclt/schema.pan]: use `legacy_binary_affirmation_string` instead.

File: ncm-afsclt/src/main/perl/afsclt.pm [hunk 6]
```diff
@@ -85,14 +88,27 @@ sub Configure_Cache {
     my $new_cache       = 0;     # in 1k blocks.
     my $file_afsmount   = '';
 
-    if ( $config->elementExists("$PREFIX/cachesize") ) {
-        $new_cache = $config->getValue("$PREFIX/cachesize");    #new cache size
-    }
-    else {
-        $self->info("Cannot get CDB $PREFIX/cachesize - not setting cache size");
+    my $afs_config = $config->getElement($PREFIX)->getTree();
```
Comment (stdweird) [inline ncm-afsclt/src/main/perl/afsclt.pm]: even better would be `$config->getTree($self->prefix())`, but maybe keep it in mind for a next time :smile:

File: ncm-afsclt/src/main/perl/afsclt.pm [hunk 7]
```diff
@@ -106,34 +122,40 @@ sub Configure_Cache {
...
 
-    my $afs_cacheinfo_fh = CAF::FileEditor->new( $AFS_CACHEINFO, log => $self ); # TODO use FileReader
-    $afs_cacheinfo_fh->cancel();
-    if ( "$afs_cacheinfo_fh" =~ m;^([^:]+):([^:]+):(\d+)$; ) {
-        $file_afsmount   = $1;
-        $file_cachemount = $2;
+    my $afs_cacheinfo_fh = CAF::FileReader->new( $AFS_CACHEINFO, log => $self );
+    $self->debug(2, "$AFS_CACHEINFO current contents: >>>$afs_cacheinfo_fh<<<");
+    if ( "$afs_cacheinfo_fh" =~ m;^([^:]+):([^:]+):(\d+|AUTOMATIC)$; ) {
+        $file_afsmount   = $1 if $file_afsmount eq "";
```
Comment (stdweird) [inline ncm-afsclt/src/main/perl/afsclt.pm]: these cannot be emtpy, since the regex have `+`; same below

File: ncm-afsclt/src/main/perl/afsclt.pm [hunk 8]
```diff
@@ -106,34 +122,40 @@ sub Configure_Cache {
...
+        $file_cachemount = $2 if $file_cachemount eq "";
         $file_cache      = $3;
-    }
-    else {
+    } elsif ( "$afs_cacheinfo_fh" ne "" ) {
         $self->error("Cannot parse stored AFS cache mount or size from $AFS_CACHEINFO");
```
Comment (stdweird) [inline ncm-afsclt/src/main/perl/afsclt.pm]: add the unparseable content in the message?

**Comment by stdweird** [comment]
@jouvin thanks for the further cleanup.

File: ncm-afsclt/src/main/perl/afsclt.pm (hunk 6 above)
Comment (jouvin) [inline ncm-afsclt/src/main/perl/afsclt.pm]: I'm working on it, not sure if it will make it in 16.6... I first want to add unit test before making the changes everywhere in the code.

File: ncm-afsclt/src/main/perl/afsclt.pm (hunk 7 above)
Comment (jouvin) [inline ncm-afsclt/src/main/perl/afsclt.pm]: I am not sure to understand... You probably misread... The point is that you use the value from the file only if it is not defined in the configuration (in which case `$file_afs_mount` is not the default empty string).

File: ncm-afsclt/src/main/perl/afsclt.pm (hunk 8 above)
Comment (jouvin) [inline ncm-afsclt/src/main/perl/afsclt.pm]: Not sure it adds anything... It is enough to look at fhe `cacheinfo` file contents.

File: ncm-afsclt/src/main/perl/afsclt.pm (hunk 7 above)
Comment (stdweird) [inline ncm-afsclt/src/main/perl/afsclt.pm]: indeed, i misread.

File: ncm-afsclt/src/main/perl/afsclt.pm [hunk 9]
```diff
@@ -106,34 +123,40 @@ sub Configure_Cache {
...
     }
 
     # adjust stored cache size (gets overwritten on restart for OpenAFS-1.4)
-    if ( $new_cache != $file_cache ) {
+    # Force string interpolation of cache size as it can be AUTOMATIC
+    if ( $file_afsmount eq "" ) {
+        $self->debug(1, "AFS mount point not defined: using default ($AFS_MOUNTPOINT_DEF)");
+        $file_afsmount = $AFS_MOUNTPOINT_DEF;
+    }
+    if ( "$new_cache" ne "$file_cache" ) {
```
Comment (stdweird) [inline ncm-afsclt/src/main/perl/afsclt.pm]: with this check, the `AFS_CACHEINIFO` is only updated is `file_cache` is modified, nit `file_afsmount` or `file_cache_mount`
i would always write the file, and with the `close` returns a change in content, do the block below.

Comment (jouvin) [inline ncm-afsclt/src/main/perl/afsclt.pm]: Good catch!

**Comment by jouvin** [comment]
As for me, ready for merging! @stdweird any other remark?!

File: ncm-afsclt/src/main/perl/afsclt.pm [hunk 10]
```diff
@@ -25,55 +25,60 @@ Readonly my $THESECELLS    => '/usr/vice/etc/TheseCells';
...
-        $self->error("Cannot get $PREFIX/thiscell (required in profile)");
+    unless ( defined($config->{thiscell}) ) {
+        $self->error("$PREFIX/thiscell missing in the configuration");
         return 1;
     }
 
-    my $afscell = $config->getValue("$PREFIX/thiscell");
     my $thiscell_fh = CAF::FileWriter->new( $THISCELL, log => $self );
-    print $thiscell_fh "$afscell\n";
+    print $thiscell_fh $config->{thiscell}."\n";
```
Comment (stdweird) [inline ncm-afsclt/src/main/perl/afsclt.pm]: there's no need for the stirng concat, `"$config->{thiscell}\n"` should also work, now that `$config` is a hashref.

**Comment by stdweird** [comment]
@jouvin LGTM (and :+1:  for further cleanup and tests)
@jrha not sure if we should wait for feedback from @ajf8 , esp if this is for 16.6.

**Comment by jouvin** [comment]
@ajf8 feedback would be great but I really think I introduced no feature changes but just fixed things that were addressing just the MS way of configuring AFS but had some flaws due to the lack of unit testing (the main change introduced by this PR!).

File: ncm-afsclt/src/main/pan/components/afsclt/schema.pan [hunk 11]
```diff
@@ -5,21 +5,20 @@
...
-   				 # "Shall AFS client be active ?"
-   "afsd_args"  ? string{} # /etc/afsd.args values for rc.afs
+   "thiscell"   : string         # AFS home cell
+   "thesecells" ? string[]       # Cell list to authenticate to
+   "settime"    ? boolean        # Shall AFS client sync sys time?
+   "cellservdb" ? string         # Where Master CellServDB can be found
+   "afs_mount"  ? string         # AFS mount point (e.g. /afs)
+   "cachemount" ? string         # AFS cache location (/usr/vice/etc/cache)
+   "cachesize"  ? string         # AFS cache size in kB
+   "enabled"    : legacy_binary_affirmation_string  # Shall AFS client be active ?
```
Comment (ned21) [inline ncm-afsclt/src/main/pan/components/afsclt/schema.pan]: IMHO this is a retrograde step for readability. I now need to locate this type defined in some other file before I can understand how to populate this mandatory field, which has no default. legacy_yes_or_no_string would be more intuitive.

Comment (jouvin) [inline ncm-afsclt/src/main/pan/components/afsclt/schema.pan]: I tend to agree... I was thinking the same thing when doing the modification suggested by @stdweird ...

Comment (stdweird) [inline ncm-afsclt/src/main/pan/components/afsclt/schema.pan]: Feel free to open an issue to change. This is work done in https://github.com/quattor/template-library-core/pull/111 and https://github.com/quattor/configuration-modules-core/issues/749; but renaming the type should be very trivial.

Comment (jouvin) [inline ncm-afsclt/src/main/pan/components/afsclt/schema.pan]: Done. https://github.com/quattor/template-library-core/issues/118.

Comment (jrha) [inline ncm-afsclt/src/main/pan/components/afsclt/schema.pan]: IMHO it would be better to make the effort to change the type to boolean instead of renaming the legacy type.

**Comment by ajf8** [comment]
Thanks for the improvements @jouvin and sorry about the break. I think this module needed some work, hopefully I got some of it done, but it looks much better now especially with the unit tests.

Please feel free to merge, I will test it sometime and submit a new pull request if anything is needed.

**Comment by stdweird** [comment]
@ajf8 thanks for the feedback
