### PR TITLE
ncm-network: handle uninitialised warning for aliases

### LINKED ISSUE #589: ncm-network 15.8.0-rc3: uninitialized value
After adding the definition of an IP alias in the machine configuration, I got the following warning when running `ncm-network`:

```
updated /tmp/_etc_sysconfig_network-scripts_ifcfg-eth0-failed
Use of uninitialized value in string eq at /usr/lib/perl/NCM/Component/network.pm line 554.
updated /tmp/_etc_sysconfig_network-scripts_ifcfg-eth0:tractest-failed
Use of uninitialized value in string eq at /usr/lib/perl/NCM/Component/network.pm line 554.
updated /tmp/_etc_sysconfig_network-scripts_ifcfg-eth0:svntest-failed
```

The config triggering the problem is:

```
+-network
  $ default_gateway : (string) '134.158.88.1'
  $ domainname : (string) 'lal.in2p3.fr'
  $ hostname : (string) 'tracsrv2'
  +-interfaces
    +-eth0
      +-aliases
        +-svntest
          $ ip : (string) '134.158.89.4'
          $ netmask : (string) '255.255.252.0'
        +-tractest
          $ ip : (string) '134.158.91.221'
          $ netmask : (string) '255.255.252.0'
      $ gateway : (string) '134.158.88.1'
      $ ip : (string) '134.158.90.164'
      $ netmask : (string) '255.255.252.0'
      $ set_hwaddr : (boolean) 'true'
    +-eth1
      $ bootproto : (string) 'dhcp'
      $ onboot : (string) 'no'
      $ set_hwaddr : (boolean) 'true'
  +-nameserver
    $ 0 : (string) '134.158.88.149'
    $ 1 : (string) '134.158.88.147'
```

The problem may have been there in previous versions of the config module...

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #589

### CODE REVIEW

**Comment by stdweird** [comment]
@jouvin can you give this a try?

**Comment by stdweird** [comment]
retest this please

File: ncm-network/src/main/perl/network.pm [hunk 1]
```diff
@@ -539,7 +539,7 @@ sub Configure
                 # ifcfg-ethY.Z:alias associated with vlan0 (and DEVICE field)
                 # problem is, we want both
                 # adding symlinks however is not the best thing to do...
-                if ($net{$iface}{vlan} eq "true") {
+                if( exists($net{$iface}{vlan}) && ($net{$iface}{vlan} eq "true") ) {
```
Comment (piojo) [inline ncm-network/src/main/perl/network.pm]: Whitespaces....

```perl
if (exits... "true")
```
