### PR TITLE
ncm-spma: fix dnf provider not to remove running kernel

### LINKED ISSUE #1565: ncm-spma: dnf provider tries to remove running kernel-core and fail
The kernel-core package on RHEL8 is a protected package as it delivers the actual kernel files and core drivers. When moving from one kernel release to another, if the running kernel is not one of listed kernels in host profile, spma will try to remove it but dnf will prevent this from happening and spma run will fail.

Looking at the code, following does exists but doesn't appear to be working as intended. 

```
   # Do not remove currently running kernel.
    my $kvers = (POSIX::uname())[2];
    $self->info("Will skip removal of running kernel: $kvers");
 
    # Compose list of packages to be installed and removed.
    my $will_remove = $preinstalled - $to_install - "kernel-$kvers" - "kernel-core-$kvers";
    my $will_install = $to_install - $preinstalled;
    $self->info("removal list: $will_remove");
```

running kernel
```
$ uname -r
4.18.0-372.13.1.el8_6.x86_64
```
this version is not listed in host profile as one of kernels to be installed.
spma run will show this, 

`[INFO] Will skip removal of running kernel: 4.18.0-372.13.1.el8_6.x86_64  `

But in the  removal list is below, the  running kernel-$kvers kernel-core-$kvers is in the list to be removed.

`[INFO] removal list: (gpg-pubkey-0:d4082792-5b32db75.(none) gpg-pubkey-0:de57bfbe-53a9be98.(none) gpg-pubkey-0:e0178866-4aeeee16.(none) gpg-pubkey-0:fd431d51-4ae0493b.(none) kernel-0:4.18.0-372.13.1.el8_6.x86_64 kernel-core-0:4.18.0-372.13.1.el8_6.x86_64 kernel-devel-0:4.18.0-372.13.1.el8_6.x86_64 kernel-headers-0:4.18.0-372.13.1.el8_6.x86_64 kernel-modules-0:4.18.0-372.13.1.el8_6.x86_64 kmod-openafs-4.18.0-372.13.1-0:1.6.24-c14.msdw.1.el8.x86_64 krb5-libs-0:1.18.2-21.el8.i686 krb5-libs-0:1.18.2-21.el8.x86_64 krb5-workstation-0:1.18.2-21.el8.x86_64 libkadm5-0:1.18.2-21.el8.x86_64)`
 
This is a bug  as $kvers has not taken into account the $epoch value thats being set in $to_install.  therefore, in this case $kver is 4.18.0-372.13.1.el8_6.x86_64 and 

kernel-core-4.18.0-372.13.1.el8_6.x86_64 != kernel-core-0:4.18.0-372.13.1.el8_6.x86_64  (notice the -0:)

* The version of the component you are using (rpm -q $component)
```
$ rpm -q ncm-spma
ncm-spma-21.12.1-1.noarch
```

* What OS version you are using (/etc/redhat-release or similar)
```
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.7 (Ootpa)
```

* Steps required to reproduce the problem
change host profile to include kernels to install which is not the running kernel.

* Actual result versus expected result
Expected result:  running kernel should not be removed by spma
actual result: spma tries to remove kernel-core.

### PR DESCRIPTION
**Pull request by aka7**
Fix bug in dnf provider to correctly exclude removal of packages core to running kernel so it doesn't try to remove running kernel.
Fixes #1565

The code to exclude the running kernel doesn't take into account the epoch value that is added in the $will_remove var. (i.e kernel-core-0: vs kernel-core. 0 is the epoch value, 0 is when no epoch value is set).  To fix this, I've now moved to do this within the existing loop which does removal for whitelist exclusion. 

* Why the change is necessary.
see issue #1565

Tested on a rhel8 host which is using the dnf provider.

### CODE REVIEW

File: ncm-spma/src/main/perl/spma/dnf.pm [hunk 1]
```diff
@@ -534,19 +534,26 @@ sub Configure
     $self->info("Will skip removal of running kernel: $kvers");
```
Comment (ned21) [inline ncm-spma/src/main/perl/spma/dnf.pm:534]: Not sure you need this info() log line any more since the real work is done later (and also logged via info()?) It records the value of $kvers but not sure that's useful enough for info.

File: ncm-spma/src/main/perl/spma/dnf.pm [hunk 2]
```diff
@@ -534,19 +534,26 @@ sub Configure
...
+    my $will_remove = $preinstalled - $to_install;
     my $will_install = $to_install - $preinstalled;
     my $whitelist = $t->{whitelist};
     my $whitelisted = Set::Scalar->new();
     for my $rpm ($will_remove->elements) {    # do not remove imported GPG keys
         if (substr($rpm, 0, 11) eq 'gpg-pubkey-') {
             $will_remove->delete($rpm);
         }
+        my $rpm_noepoch = $rpm;
+        $rpm_noepoch =~ s/^.*://;
```
Comment (ned21) [inline ncm-spma/src/main/perl/spma/dnf.pm:546]: My expectation of a variable called `$rpm_noepoch` is that it's the whole thing without an epoch, but looking carefully at the substitution it removes everything before the (last) colon, making the variable more accurately named, `$rpm_version_noepoch` ?

I might be tempted to go for something like this as being a bit more readable than a regex too (but maybe I'm just out of tune with Perl ;-)
```
$rpm_version = (split(':', $rpm))[-1];
```

File: ncm-spma/src/main/perl/spma/dnf.pm (hunk 1 above)
Comment (aka7) [reply ncm-spma/src/main/perl/spma/dnf.pm:534]: was debating about this myself. I agree, don't think it's much of a useful info.

File: ncm-spma/src/main/perl/spma/dnf.pm (hunk 2 above)
Comment (aka7) [reply ncm-spma/src/main/perl/spma/dnf.pm]: Make sense thanks.

**Comment by ned21** [comment]
LGTM but I'll leave someone from outside MS to approve.

**Comment by aka7** [comment]
@jrha would you be able to take a look at this? I believe only MS is using the dnf provider. 
If all is ok, we would like to get this into current release of 21.12.1 if possible ?

**Review by jrha — APPROVED** [review]
