### PR TITLE
ncm-network: nmstate dgw fix

### LINKED ISSUE #1655: ncm-network: nmstate default gateway issue
@aka7 I found another discrepancy with nmstate, with gateways. on our site we only set `/system/network/default_gateway`. something like:
```
+-/system/network
  $ default_gateway : '10.141.10.250'
  $ domainname : 'domain'
  $ hostname : 'hostname'
  +-interfaces
    +-eth0
      $ broadcast : '10.141.31.255'
      $ driver : 'bnx2'
      $ ip : '10.141.10.62'
      $ netmask : '255.255.224.0'
      +-route
        +-0
...
```

but in the code I see:
```
    if ($default_gw) {
        # create only default gw entry if gw entry match interface gateway defined                                                                           
        # otherwise this interface is not the default gw interface.                                                                                          
	if ((defined($iface->{gateway})) and ($iface->{gateway} eq $default_gw)) {
            $default_rt{destination} = '0.0.0.0/0';
            $default_rt{'next-hop-address'} = $default_gw;
            $default_rt{'next-hop-interface'} = $device;
	}
    }
```

the `defined($iface->{gateway})` always fails, so no default gateway is set. My perl is quite poor but it seems the code makes the assumption that a gateway is set on interface level. while network.pm does not. Unless I'm mistaken.

I would expect a route like the following to show up:
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.141.10.250   0.0.0.0         UG    0      0        0 eth0
```

### PR DESCRIPTION
**Pull request by aka7**
Fix for setting default gateway in nmstate with correct interface by looking up if gateway falls within subnet boundary.
next-hop-interface is mandatory for nmstate therefore figure out which interface subnet this gateway falls in. 
This will provide backward compatibility with network.pm

closes #1655 

* Why the change is necessary.
to provide backward compatibility with network.pm when setting default gateway. without having to set gateway address on interface.

* What backwards incompatibility it may introduce.
None.

### CODE REVIEW

**Comment by wdpypere** [comment]
@aka7 thanks for the quick work. I can confirm this code now does with default gateways what I would expect!

**Comment by aka7** [comment]
> @aka7 thanks for the quick work. I can confirm this code now does to default gateways what I would expect!

thanks for confirming, I've opened this PR for review now. I think this will be better then what I had before as I assumed every interface will have gateway defined.

Also bear in mind, nmstate module does not provide all functionalities currently provided by network.pm, as many of comments in the nmstate.pm states. @wdpypere

File: ncm-network/src/main/perl/nmstate.pm [hunk 1]
```diff
@@ -296,6 +296,17 @@ sub generate_vip_config {
     return $iface_cfg;
 }
 
+# Check if given ip belongs to a network
+sub ip_in_network {
+    my ($self, $check_ip, $ip, $netmask) = @_;
+    # is the given gw ip in his ip/netmask.
```
Comment (stdweird) [inline ncm-network/src/main/perl/nmstate.pm:302]: remove `gw` in comment, this is about any ip

File: ncm-network/src/main/perl/nmstate.pm [hunk 2]
```diff
@@ -296,6 +296,17 @@ sub generate_vip_config {
...
+    my $thisip = NetAddr::IP->new("$check_ip");
```
Comment (stdweird) [inline ncm-network/src/main/perl/nmstate.pm:303]: why not 
```
my $subnet = NetAddr::IP->new("$ip", "$netmask");
return NetAddr::IP->new("$check_ip")->within($subnet);
```

**Comment by stdweird** [comment]
@aka7 can you also have a look at this?

**Review by stdweird — APPROVED** [review]
