### PR TITLE
ncm-spma: enhance dnf provider to allow update to newer streams.

### LINKED ISSUE #1565: ncm-spma: dnf provider tries to remove running kernel-core and fail
The kernel-core package on RHEL8 is a protected package as it delivers the actual kernel files and core drivers. When moving from one kernel release to another, if the running kernel is not one of listed kernels in host profile, spma will try to remove it but dnf will prevent this from happening and spma run will fail.

Looking at the code, following does exists but doesn't appear to be working as intended. 

```
   # Do not remove currently running kernel.
    my $kvers = (POSIX::uname())[2];
    $self->info("Will skip removal of running kernel: $kvers");
 
    # Compose list of packages to be installed and removed.
    my $will_remove = $preinstalled - $to_install - "kernel-$kvers" - "kernel-core-$kvers";
    my $will_install = $to_install - $preinstalled;
    $self->info("removal list: $will_remove");
```

running kernel
```
$ uname -r
4.18.0-372.13.1.el8_6.x86_64
```
this version is not listed in host profile as one of kernels to be installed.
spma run will show this, 

`[INFO] Will skip removal of running kernel: 4.18.0-372.13.1.el8_6.x86_64  `

But in the  removal list is below, the  running kernel-$kvers kernel-core-$kvers is in the list to be removed.

`[INFO] removal list: (gpg-pubkey-0:d4082792-5b32db75.(none) gpg-pubkey-0:de57bfbe-53a9be98.(none) gpg-pubkey-0:e0178866-4aeeee16.(none) gpg-pubkey-0:fd431d51-4ae0493b.(none) kernel-0:4.18.0-372.13.1.el8_6.x86_64 kernel-core-0:4.18.0-372.13.1.el8_6.x86_64 kernel-devel-0:4.18.0-372.13.1.el8_6.x86_64 kernel-headers-0:4.18.0-372.13.1.el8_6.x86_64 kernel-modules-0:4.18.0-372.13.1.el8_6.x86_64 kmod-openafs-4.18.0-372.13.1-0:1.6.24-c14.msdw.1.el8.x86_64 krb5-libs-0:1.18.2-21.el8.i686 krb5-libs-0:1.18.2-21.el8.x86_64 krb5-workstation-0:1.18.2-21.el8.x86_64 libkadm5-0:1.18.2-21.el8.x86_64)`
 
This is a bug  as $kvers has not taken into account the $epoch value thats being set in $to_install.  therefore, in this case $kver is 4.18.0-372.13.1.el8_6.x86_64 and 

kernel-core-4.18.0-372.13.1.el8_6.x86_64 != kernel-core-0:4.18.0-372.13.1.el8_6.x86_64  (notice the -0:)

* The version of the component you are using (rpm -q $component)
```
$ rpm -q ncm-spma
ncm-spma-21.12.1-1.noarch
```

* What OS version you are using (/etc/redhat-release or similar)
```
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.7 (Ootpa)
```

* Steps required to reproduce the problem
change host profile to include kernels to install which is not the running kernel.

* Actual result versus expected result
Expected result:  running kernel should not be removed by spma
actual result: spma tries to remove kernel-core.

### PR DESCRIPTION
**Pull request by aka7**
change dnf provider to reset module stream on config change to allow updates to happen on next spma run.

Fixes #1565

* Why the change is necessary.
To allow changes to streams without having to rebuild, or run commands manually.
* What backwards incompatibility it may introduce.
none.

### CODE REVIEW

File: ncm-spma/src/main/perl/spma/dnf.pm [hunk 1]
```diff
@@ -125,7 +125,15 @@ sub generate_dnf_modules {
         my $fh = $trd->filewriter("$directory/$name.yaml",
                                   header => "# File generated by " . __PACKAGE__ . ". Do not edit",
                                   log => $self);
-        $changes += $fh->close() || 0; # handle undef
+        $module_changed += $fh->close() || 0; #handle undef
+        $changes += $module_changed; 
+        if ($module_changed > 0 and !$CAF::Object::NoAction) {
+            my ($cmd_exit, $cmd_out, $cmd_err) = $self->execute_command([DNF_MODULE_RESET, $name], "module stream change detected. Reset managed module stream ".$name." for update", 1, "/dev/null", 1);
```
Comment (ned21) [inline ncm-spma/src/main/perl/spma/dnf.pm:131]: This line is unreadably long, can you break it up so it wraps a bit more easily please? Also I don't see any reason not to use string interpolation here? 

"module stream change detected. Reset managed module stream $name for update"

File: ncm-spma/src/main/perl/spma/dnf.pm [hunk 2]
```diff
@@ -125,7 +125,15 @@ sub generate_dnf_modules {
...
+            if ($cmd_exit) {
+                $self->error("Error during reset module ". $cmd_err);
```
Comment (ned21) [inline ncm-spma/src/main/perl/spma/dnf.pm:133]: Use "Error during reset module $cmd_err"

The only reason to use concat (.) is if you need to use ' instead of "

**Review by ned21 — COMMENTED** [review]
Minor formatting. Am I right in thinking we're the only site to use this so we're OK to merge this without explicit approval from another site?

File: ncm-spma/src/main/perl/spma/dnf.pm (hunk 1 above)
Comment (aka7) [reply ncm-spma/src/main/perl/spma/dnf.pm]: updated

File: ncm-spma/src/main/perl/spma/dnf.pm (hunk 2 above)
Comment (aka7) [reply ncm-spma/src/main/perl/spma/dnf.pm]: Thanks. updated

File: ncm-spma/src/main/perl/spma/dnf.pm (hunk 1 above)
Comment (aka7) [reply ncm-spma/src/main/perl/spma/dnf.pm]: and yes I believe DNF provider is not used by anyone else. We started using on rhel8 builds.

**Review by ned21 — APPROVED** [review]
