### PR TITLE
ncm-opennebula: Set oned.conf and more bug fixes

### LINKED ISSUE #351: ncm-opennebula: system datastore is set to shared as default
Create a new hook to change system datastore TM.

### LINKED ISSUE #365: ncm-opennebula: generate oned.conf from component
Create a new function to generate oned.conf directly from opennebula component

### LINKED ISSUE #368: ncm-opennebula: include QUATTOR flag for every resource managed by quattor
QUATTOR flag is missing in the current hosts managed by the component. Update the host templates to set quattor flag. 
Update system datastore with QUATTOR flag if its required as well.

### LINKED ISSUE #369: ncm-opennebula: set a list of untouchable resources
For every resource managed by quattor set a list of untouchables. Opennebula component will not change those resources (even if quattor flag is set to 1).

### PR DESCRIPTION
**Pull request by alvarosimon**
Requires #350 to be merged in 

This PR fixes these issues:
 * Fix #369 set a list of untouchable resources
 * Fix #368 include QUATTOR flag for every resource managed by quattor (hosts)
 * Fix #351 system datastore is set to shared as default
 * Fix #365 generate oned.conf from component

### CODE REVIEW

File: ncm-opennebula/src/main/perl/opennebula.pm [hunk 1]
```diff
@@ -65,9 +69,9 @@ sub process_template
 
 # Create/update ONE resources
 # based on resource type
-sub set_resource
+sub create_or_update_something
 {
-    my ($self, $one, $type, $data) = @_;
+    my ($self, $one, $type, $data, %untouch) = @_;
```
Comment (piojo) [inline ncm-opennebula/src/main/perl/opennebula.pm]: `untouch` is an ugly name. `protected` matches your comments below.

File: ncm-opennebula/src/main/perl/opennebula.pm [hunk 2]
```diff
@@ -95,10 +103,11 @@ sub set_resource
     return $new;
 }
 
+
 # Removes ONE resources
 sub remove_something
 {
-    my ($self, $one, $type, $resources) = @_;
+    my ($self, $one, $type, $resources, %untouch) = @_;
```
Comment (piojo) [inline ncm-opennebula/src/main/perl/opennebula.pm]: As above.

File: ncm-opennebula/src/main/perl/opennebula.pm [hunk 3]
```diff
@@ -306,12 +316,21 @@ sub change_oneadmin_passwd
...
+}
+
 # Remove/add ONE resources
 # based on resource type
 sub manage_something
 {
-    my ($self, $one, $type, $resources) = @_;
-
+    my ($self, $one, $type, $resources, $untouchables) = @_;
+    my %untouch = map { $_ => 1 } @$untouchables;
```
Comment (piojo) [inline ncm-opennebula/src/main/perl/opennebula.pm]: Actually, I'd use `Set::Scalar` instead of this. SPMA already depends on it, so you wouldn't be adding any extra dependencies.

File: ncm-opennebula/src/main/perl/opennebula.pm [hunk 4]
```diff
@@ -476,6 +504,48 @@ sub manage_users
...
+        $self->restart_opennebula_service();
+    }
+    return 1;
+}
+
+sub set_oned_file_opts
+{
+    my ($self) = @_;
+    my %opts;
+    if (getpwnam("oneadmin") and getpwnam("oneadmin")) {
```
Comment (piojo) [inline ncm-opennebula/src/main/perl/opennebula.pm]: What is this? Why these two calls to `getpwnam` with the same arguments?

Comment (piojo) [inline ncm-opennebula/src/main/perl/opennebula.pm]: Do you mean `getpwnam("oneadmin") and getgrnam("oneadmin")`?

Comment (alvarosimon) [inline ncm-opennebula/src/main/perl/opennebula.pm]: ups.. yep exactly :sweat_smile:

**Comment by jouvin** [comment]
Any good reason not to put it in 15.2... This is already an old PR...

**Comment by stdweird** [comment]
@jouvin it's not properly reviewed, and with `1.42` build-tools out, i will clean up some tests too

**Comment by stdweird** [comment]
@jrha rereviewed, looks ok to me

**Comment by jrha** [comment]
Thanks, it was a bit too much for me :stuck_out_tongue:
