### PR TITLE
ncm-network: Fix ovs_extra network script output

### LINKED ISSUE #651: ncm-network: ovs_extra is not set correctly
If you set ovs_extra conf from quattor the component encloses the text into single quotes instead of double quotes, for example if you set in quattor:
> "ovs_extra", 'set Interface $DEVICE type=internal',

you get from the network conf file:
> OVS_EXTRA='set Interface $DEVICE type=internal'

and the variable is not expanded, from OVS logs:
> ovs-vsctl: ovs|00001|vsctl|INFO|Called as ovs-vsctl -t 10 -- --may-exist add-br br100 -- set Interface $DEVICE type=internal
> ovs-vsctl: ovs|00002|vsctl|ERR|no row "$DEVICE" in table Interface

It should be:
> OVS_EXTRA="set Interface $DEVICE type=internal"

It could be fixed from network.pm just including double quotes:
> 294                     $text .= "OVS_EXTRA=\"$net{$iface}{ovs_extra}\"\n";

### PR DESCRIPTION
**Pull request by alvarosimon**
* Fix #651 : ovs_extra is not set correctly

### CODE REVIEW

File: ncm-network/src/main/perl/network.pm [hunk 1]
```diff
@@ -279,7 +279,7 @@ sub Configure
                     $text .= "OVS_OPTIONS='$net{$iface}{ovs_opts}'\n";
```
Comment (stdweird) [inline ncm-network/src/main/perl/network.pm]: also here? if we would do this for the whole component, we better have a TT file create this. but this will trigger a mass network restart

Comment (alvarosimon) [inline ncm-network/src/main/perl/network.pm]: I think that is only required by `OVS_EXTRA` the rest of OVS options do not include variables. 
https://github.com/asteven/openvswitch/blob/master/rhel/README.RHEL

Comment (stdweird) [inline ncm-network/src/main/perl/network.pm]: ok

**Comment by stdweird** [comment]
LGTM
